frewsxcv/rust-crates-index

Cargo.toml

Currently, on the crates.io page, there is only a link to this repository page. This commit/pr will add a link to the documentation so that users can find it straight from the crates.io page.

Add documentation link to Cargo.toml

---

Cargo.toml

This crate won't even build today, given that the dependencies now produce a divergent requirement on `libz`:
```
native library `z` is being linked to by more than one package, and can only be linked to by one package
libz-sys v0.1.9
libz-sys v1.0.0
```
Updating git2 fixes this.
I also included a commit to release a new version with this update, that'd be great if you could :)

Update git2 dependency and bump version

---

.gitignore
.travis.yml
Cargo.toml

1. update the git2 version so conflicts with openssl-sys don't happen
2. add generated directory to .gitignore
3. bump version
If you could publish this to crates.io too, that'd be great :heart:

Some small fixes

---

src/lib.rs

This also means that `Index` can implement the Clone trait if you want.

Rename `clone()` to `fetch()`.

---

src/lib.rs

It's more idiomatic for `Index::new()` to accept anything which can be converted into a `PathBuf`. I also added a couple derives and a `path()` getter to make debugging easier.

Made the Index more generic and implement Debug

---

src/lib.rs

Useful when you want to save the crate data somewhere yourself, eg a file, key value store, etc.
(need  this myself.)

Allow data types to be serialized.

---

Cargo.toml

It doesn't fit any category exactly, but git-related tools are mostly in `development-tools`, and the crates index is a sort of a database, so it can be in database interfaces category, too.

Add categories

---

src/lib.rs

I've had
```
for path in index.crate_index_paths() {
let k = Crate::new(path);
}
```
and discovered it was O(n²) expensive (scanning the index 30001 times), yikes!

Generate path instead of searching for it

---

src/lib.rs

* Use shorthand struct initialization syntax
* Remove redundant `'static`
* Simplify getters by using `Option::as_deref()`
`Option::as_deref()` became stable fairly recently, in Rust v1.40.

Fix some clippy lints

---

Cargo.toml
src/lib.rs

* Error-chain is an overkill for 1 error case
* `Crate::new` should be fallible
* Checksum can take 32 bytes instead of 80+
* Dependency kind doesn't need to be a string. It's parsed as an option to make serde happy, but the default is "normal", so the API can just return the default instead of `None`.

Breaking changes

---

Cargo.toml
src/lib.rs

This method does return the latest version as specified by the semantic
version specification instead of the "youngest" version of a crate.
Closes #20

add `latest_semver_version` method

---

Cargo.toml
src/bare_index.rs
src/error.rs
src/lib.rs

This mostly resolves #17, though it just supports reading specific crates, not iteration, though that could be added if desirable.
* Adds `BareIndex` which is just a wrapper around a repository url and a local path
* Adds `BareIndexRepo` which is created via `BareIndex::open_or_clone()` and keeps a the git repository details needed for reading crate contents on demand, and allows fetching updates
* Adds support for reading cargo's `.cache` entries, which are created by cargo whenever it reads a crate from the index so that it doesn't have to fetch the git blob, but falls back to reading the entry from the git blob if the cache entry doesn't exist.
Additional:
* Fixed a bug where 3 letter long crate names were skipped when iterating

Add support for bare repos

---

src/bare_index.rs

The crates.io index is known to safely convert to a path, don't force
the caller to consider errors in this case.

Inline unwrap

---

src/bare_index.rs
src/lib.rs

https://stackoverflow.com/a/27320456/831850 claims "Actually, by default, Clone() takes care of locally retrieving all commits of all branches. By default, only the remote HEAD branch (generally origin/master), gets an automatically created local branch counterpart, which is then checked out."
Copying some code from https://github.com/rust-lang/cargo/blob/963bfe4dd9e3b35738182f4e1667c0197d2ab60c/src/cargo/sources/registry/remote.rs#L95
I was able to get the same size checkouts as cargo for bareindex and double cargos size for normal indexes.
I don't know much about this, so fixes are welcome, but this seemed like a good POC.
Fix #47

Reduce the size of checkouts

---

src/lib.rs

In cargo, [`HEAD`] is updated instead of `master`. This mismatch means that the two refs can drift, depending on when cargo and this library last fetched changes.
I believe this change will fix sunng87/cargo-release#224. In that bug, it is first confirmed (by fetching `master`) that a recently published crate is now available in the public index. Once the dependency is published, it should be safe to publish new crates which depend on it. However, when the next crate is published the local build fails because `cargo` is using a less recent `HEAD`, which was not updated by `crates-index`.
The change brings this implementation into alignment with [`src/bare_index.rs`].
[`HEAD`]: https://github.com/rust-lang/cargo/blob/0b2059e9811caa238a603f0300d9c5fb485000a6/src/cargo/sources/registry/remote …

Checkout `HEAD` instead of `master`

---

src/bare_index.rs
src/error.rs
src/lib.rs

This is described in https://doc.rust-lang.org/cargo/reference/registries.html#index-format
and allows parsing out download URLs for crates in the index.

Allow parsing config.json data from an index

---

src/bare_index.rs
src/lib.rs
tests/mem.rs

Fixes #73 
I added the constraints as Warnings and listed Unconstrained to signal this.
I realised that CI doesn't enforce rustfmt so there is some minor rustfmt in addition (sowwy!)

docs + fmt: Unconstrained expectations

---

Cargo.toml

I was upgrading dependencies for in docs.rs, and stumbled onto this issue. 
Problem is that `git2` upgraded `libgit2-sys` to `1.4.0`, which then leads to a conflict (_failed to select a version for `libgit2-sys`_) when an application has the `git2==0.14.0` in its dependencies.

upgrade `git2` dependency

---

Cargo.toml
src/bare_index.rs
src/lib.rs

Deprecation note here: https://crates.io/crates/tempdir

replace tempdir crate with tempfile, as tempfile have superseded tempdir

---

src/bare_index.rs

I am writing code to publish to different indexes.
For debugging, it would be nice to be able to distinguish between the various indexes.

expose index url

---

README.md

The correct name is `most_recent_version`:
https://docs.rs/crates-index/0.18.11/crates_index/struct.Crate.html#method.most_recent_version

Fix method name in readme

---

Cargo.toml
src/lib.rs

Hi and thank you for this very useful project :pray: 
I noticed that in https://github.com/frewsxcv/rust-crates-index/commit/7e945b37dc94a442438bd1d8c2da9ee81ac3f0ad, `smol_str` was replaced by `smartstring` for MSRV reasons.
What is the MSRV for this project? Is it higher than 1.45? If so, we should be able to go back to `smol_str`. I can run `cargo test` on `smol_str` with 1.46, but not 1.45. So I think the effective MSRV of `smol_str` `0.1.23` is 1.46.
The downside of `smartstring` is that it is licensed under MPL 2.0, which has a copyleft flavor to it, which some can find concerning. `smol_str` is `MIT OR APACHE-2.0`.
Inte: The officiell MSRV policy of `smol_str` is "latest stable". Maybe that is a problem. Another option to this PR could be to add a feature where `smol_str` OR …

Start using `smol_str` again to avoid MPL 2.0 license of `smartstring`

---

src/bare_index.rs

Do not assume that `/` is the system's path separator char.

---

Cargo.toml

Currently, it is not possible to enable `https` without also enabling `parallel`.

Allow enabling the https feature by itself

---

src/lib.rs

This was added to the index in rust-lang/crates.io#6267.  crates.io is automatically injecting it into the index, even without using the nightly cargo that supports it.
My plan is to use this to make cargo-upgrade more MSRV aware (in version reqs despite the resolver not yet being MSRV aware).

feat: Add support for 'rust_version'

---

tests/mem.rs

Reported mem usage both locally and in CI is ~6080 bytes which makes the test fail. Increase threshold from 6000 to 6200 bytes to fix CI.
Other PRs' CI fails because of this,  e.g.
* #107 
* #109

Increase threshold in mem_usage() test from 6000 to 6200

---

src/dirs.rs

While doing another PR I noticed this bug in the hash calculation used to find the local index directory for a registry, the use of usize would result in different hashes on 32-bit architectures. Apparently this is not an issue since no one has complained AFAICT, but might as well fix it to potentially save some pain in the future.
See https://github.com/EmbarkStudios/cargo-deny/pull/374

Fix hash calculation on 32-bit targets

---

rustfmt.toml

[Rustfmt](https://github.com/frewsxcv/rust-crates-index/pull/110#issuecomment-1592098714) is not wanted for this project, so adding this config globally disables it as most users have things like applying rustfmt on save or the like.

Disable rustfmt

---

rustfmt.toml
src/bare_index.rs
src/dirs.rs
src/lib.rs
src/sparse_index.rs

- Disable rustfmt
- Add CRATES_IO_HTTP_INDEX
Also moves the git index url to the bare_index for clarity
This also fixes 2 bugs:
1. The SparseIndex::from_url was not validating that the url started with `sparse+`, which is required as it is part of the hash calculation and would result in incorrect disk locations if the user forgot to add that in the url
2. The hash calculation was incorrect, in cargo, only git registries use the hash of the canonicalized url for the ident, all other registry kinds just hash the raw url

Add CRATES_IO_HTTP_INDEX

---

rustfmt.toml
src/bare_index.rs
src/lib.rs
src/sparse_index.rs

- Disable rustfmt
- Fix cache deserialization
Cargo 1.52.0 changed the cache entry version, from 1 -> 2 (it is now 3) which means that this crate has been doing the much more expensive reading from the git blobs rather than (valid) .cache entries for over 2 years. This was fixed by simply combining the git and sparse cache reading into a single function, as the sparse one was correctly reading current 1.54.0+ .cache entries, which are the same regardless of the index type. No one has noticed this because any .cache errors are simply [swallowed](https://github.com/frewsxcv/rust-crates-index/blob/5db087328bc11340c6f6c715ad978d7fc5c9ec69/src/bare_index.rs#L232) by the current code.

Fix cache deserializatoin

---

rustfmt.toml
src/bare_index.rs
src/dirs.rs
src/lib.rs
src/sparse_index.rs

- Disable rustfmt
- Add CRATES_IO_HTTP_INDEX
- Cleanup index initialization
This exposes a new `get_index_details` function that takes a url and turns it into the disk location, rooted at the optional location or CARGO_HOME/cargo default, as well as the canonicalized url. This also adds `SparseIndex::with_path` which allows a user to easily create a sparse index at the specific location but still with the same layout as cargo and _not_ be dependent on CARGO_HOME. This meant `sparse_index::test::parses_cache` could be drastically simplified to remove the mucking about with environment variables.

Cleanup index initialization

---

src/bare_index.rs
src/lib.rs

To make it easier to turn git2 into an optional dep.
This was originally done in https://github.com/frewsxcv/rust-crates-index/pull/107, but I am creating a separate PR for it to make it easier to review and to reduce risk of conflicts between PRs (or at least make them easier to sort out).

refactor: Move private fn fetch_opts() into mod bare_index

---

src/bare_index.rs
src/lib.rs

To make it easier to turn git2 into an optional dep.
Continuation of #111 to reduce size of #107.

refactor: Move Index tests to base_index mod

---

src/lib.rs

currently, it seems like when using sparse-index all features in features2 are ignored. 
This PR fixes this and additionally dedupes the data
note:
maybe somebody can think of a better name for `build_data`

use features2 when using sparse-index

---

Cargo.toml
src/bare_index.rs
src/dirs.rs
src/error.rs
src/lib.rs
tests/mem.rs

To adapt to the sparse crates.io index, I [have stopped](https://github.com/Enselic/cargo-public-api/pull/439) using the git index code from crates-index, and only use the `Crate` code, in particular [`Crate::from_slice`](https://docs.rs/crates-index/0.19.10/crates_index/struct.Crate.html#method.from_slice), since that works with the HTTP response of the sparse index:
```
$ curl https://index.crates.io/ex/am/example_api
{"name":"example_api","vers":"0.1.0","deps":[],"cksum":"d0f99c425515721620183a74993ebb809ca7f06c4e6b09b8c28668d56a2e78fd","features":{},"yanked":false}
{"name":"example_api","vers":"0.1.1","deps":[],"cksum":"3fc31d0e953c46287ea7ddb2f5cd93f0b8eae0ec9777f75569b9d3b7837c14bc","features":{},"yanked":false}
{"name":"example_api","vers":"0.2.0","deps":[],"cksum":"67c4a4db10e5e112 …
```

For 0.20.0: Make git2 dependency optional via new "git-index" feature

---

src/lib.rs

When making `git2` optional, an issue with compiling doc tests was introduced.
----
This indeed [seems to fix CI](https://github.com/Byron/rust-crates-index/actions/runs/5584898603/jobs/10206917559).

Fix doc tests (and CI with it)

---

.github/workflows/cargo.yml
.gitignore
Cargo.toml
examples/update_and_get_latest.rs
src/bare_index.rs
src/changes.rs
src/error.rs
src/lib.rs
tests/mem.rs

This PR replaces `git2` with `gix`. It does so trying to make no breaking changes to the public API.
*Please note that this is an ongoing effort, this PR will change a lot.*
With the sparse index slowly becoming the new default, users of this crate will probably be less succeptible
to changes in the `git` implementation which might come with compatibility issues on windows when `ssh` is used.
Furthermore, `gix` now has a robust implementation of the negotiation protocol which allows it to work for 
crates.io proxies as well, which is important for users in China.
Making this changes has high value as it can solve a list of issues which have been open for a long time.
* The `vendored-openssl` feature toggle was removed as there is no equivalent, additive feature in `gitoxide`. It's …

Replace `git2` with `gix`

---

.github/workflows/cargo.yml
src/sparse.rs

always use / as a separator for sparse urls

---

Cargo.toml
src/lib.rs
src/names.rs
tests/crates_index.rs
tests/names/mod.rs

This PR adds the in #75 suggested `NamesIter`
open Questions:
- how to handle too many `-_`?
In case of more than 32 separators, the programs would just crash with an `attempt to multiply with overflow`.
I don't think handling it as a `Result<>` would be reasonable as this case is not realistic and using `Result<>` would make the API worse (at least in my opinion)
- should the iter return `&str`?
note:
I am not really happy with the code but every attempt of improving it just made it worse...

NamePermutationIterator

---

src/names.rs

This PR fixes a small typo in the `Names` doc

fix typo in Names doc

---

src/names.rs
tests/names/mod.rs

This PR adds some small improvements to `Names`
- overwriting `count()` to improve performance
I added a 'custom' `count()` for tests as they otherwise would not really test the functionality 
- it now returns `input`, `all-hyphens`, `all_underscores`, `…all remaining permutations…`

minor Names optimizations

---

Cargo.toml

when running the `update_and_get_latest` example you get this error when only using the `git` feature 
`Error: Git(RemoteConnect(Connect(CompiledWithoutHttp(Https))))`

example "update_and_get_latest" requires "git-https"

---

Cargo.toml
src/error.rs
src/git/mod.rs
src/git/test.rs
src/lib.rs
tests/git/mod.rs

Related to #62 .
See what should be done about locking.

locking behaviour improvements

---

Cargo.toml
src/git/impl_.rs
tests/git/mod.rs
tests/mem.rs

gix upgrade

---

Cargo.toml
examples/sparse_http_reqwest.rs
examples/sparse_http_ureq.rs

This PR updates the `sparse_http_ureq` example to use ureq 2.8.0 which enables a simpler type conversion.

update sparse_http_ureq to use ureq 2.8.0

---

Cargo.toml
examples/update_and_get_latest.rs
examples/update_and_get_most_recent_version.rs
src/git/impl_.rs

- chore: upgrade `http` to v1.0
- add new example to list the most recent version of a crate using the git index
Also validated that git index updates work as they should, and it indeed seems to be the case.

update `http` and add example

---

src/git/impl_.rs

The remote git repository may alter its references in such a way that
local fast-forwards aren't possible anymore.
This happens regularly as the history will be squashed on the remote.
Now we forcefully store the updated references, which resolves
the issue that calling `update()` didn't seem to do anything despite
being busy (i.e. downloading a possibly huge pack, and resolving it).

fix: assure Git index updates to refs are actually written.

---

Cargo.toml

Right now `cargo check -F git` is broken.
Error:
```
error[E0599]: the method `context` exists for fn item `fn(&mut &[u8]) -> Result<SignatureRef<'_>, ErrMode<_>> {decode::<'_, _>}`, but its trait bounds were not satisfied
--> /Users/marcoieni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-ref-0.41.0/src/store/file/log/line.rs:142:46
|
142 |                 gix_actor::signature::decode.context(StrContext::Expected("<name> <<email>> <timestamp>".into())),
|                                              ^^^^^^^ method cannot be called due to unsatisfied trait bounds
|
= note: the following trait bounds were not satisfied:
`<for<'a> fn(&'a mut &[u8]) -> Result<SignatureRef<'_>, winnow::error::ErrMode<_>> {gix_actor::signature::decode::<'_, _>} as FnOnce<(&mut _,)>>::Output = …
```

chore: update to gix v0.59

---

src/sparse.rs
tests/fixtures/config.json
tests/sparse_index/mod.rs

Add support for downloading the sparse index config

---

README.md

Changed Index to GitIndex. The Index struct had its name changed to GitIndex in crates_index v2.0, resulting in the example code in the README not compiling.

Correct Example Code In README

---

Cargo.toml
examples/list_recent_versions.rs
examples/sparse_http_ureq.rs

This PR upgrades the `http` dependency to version 1. This allows [directly converting from `reqwest::Response` to `http::Response`](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#impl-From%3CResponse%3E-for-Response%3CBody%3E) rather than manually building the response as [shown in the example](https://github.com/frewsxcv/rust-crates-index/blob/4be1703d13817d76896f98084ee1a06a2533125a/examples/sparse_http_reqwest.rs#L44-L52). Note that this conversion is only implemented for regular (async) responses, so the example (which uses `reqwest::blocking`) remains unchanged.

Upgrade to http 1

---

src/types.rs

This commit exposes the field `registry` on the `Dependency` struct. This field is always set by `cargo`, and it's needed to properly handle dependencies when multiple registries are used.

feature: expose dependency registry url

---

Cargo.toml
src/git/changes.rs
src/git/impl_.rs
src/lib.rs
tests/git/mod.rs
tests/mem.rs

A minimal API to solve my needs for #178.
Is this roughly what you had in mind?  How would you like it tested? How would you like to see error handling dealt with?

Set commit

---

.github/workflows/cargo.yml
tests/git/mod.rs

I've been using this platform in my last PR and everything works just as expected. Figured it would be a good idea to include this so there's some kind of signal if the platform breaks.

Add MacOS to CI matrix

---

Cargo.toml
src/dirs.rs
src/git/impl_.rs
src/lib.rs
src/sparse.rs
src/types.rs

closes https://github.com/frewsxcv/rust-crates-index/issues/182

Add support for new index hash implementation.

---

src/dirs.rs

- See issue in [rules_rust ](https://github.com/bazelbuild/rules_rust/issues/3310)
- Seems like @UebelAndre [PR ](https://github.com/frewsxcv/rust-crates-index/pull/184) broke custom crates repositories hashing that ended with a slash. 
- Removing slashes on urls with paths seems to have fixed the issue.  I was able to patch this through to rules rust and confirmed it work

Fix urls with trailing slashses with paths
